//Carolina Rodriguez
//CSD-420
// Assignment 8 
// Three Threads- Letters, numbers and symbols displaying in a TextArea. 

//Resources:

//GeeksforGeeks. (2025, April, 28). Java JScrollBar.https://www.geeksforgeeks.org/java/java-jscrollbar/
//GeeksforGeeks. (2025, July 23). Java AWT vs Java Swing vs JavaFX. https://www.geeksforgeeks.org/java/java-awt-vs-java-swing-vs-java-fx/
//GeeksforGeeks. (2022, May 10). Java Swing | JTextArea.https://www.geeksforgeeks.org/java/java-swing-jtextarea/
//freeCodeCamp.org. (2024, July 15). Multithreading for beginners [Video]. YouTube. https://www.youtube.com/watch?v=gvQGKRlgop4
//Oracle. (n.d.). How to make frames (main windows). Java Tutorials.https://docs.oracle.com/javase/tutorial/uiswing/components/frame.html

import javax.swing.*;
import java.awt.*;
import java.util.Random;

public class Carolina_ThreeThreads extends JFrame {

    private JTextArea textArea; // Shared TextArea for all threads
    private final int LIMIT = 10000; //limit for characters generated by each thread

    public Carolina_ThreeThreads() {

//GUI
        setTitle("Three Threads Assignment");
        setSize(500, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        textArea = new JTextArea();
        textArea.setLineWrap(true); // Wrap text for better display

        add(new JScrollPane(textArea), BorderLayout.CENTER); // Add TextArea with scroll

        setVisible(true); // Show the GUI

        
        startThreads();
    }

//Threads
    private void startThreads() {

//Letters
        Thread letters = new Thread(() -> generateChars("abcdefghijklmnopqrstuvwxyz"));
//Numbers
        Thread numbers = new Thread(() -> generateChars("0123456789"));

//Symbols
        Thread symbols = new Thread(() -> generateChars("!@#$%&*"));

        letters.start();
        numbers.start();
        symbols.start();
    }


    private void generateChars(String source) {

        Random random = new Random();
//limit for characters generated by each thread
        for (int i = 0; i < LIMIT; i++) {

            char c = source.charAt(random.nextInt(source.length())); // Randomly select a character from string


            SwingUtilities.invokeLater(() -> { // Update TextArea 
                textArea.append(String.valueOf(c));
            });

            try {
                Thread.sleep(1); // Sleep to slow down the generation for better visualization
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new Carolina_ThreeThreads()); 
    }
}